version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5673"
      - "15673:15673"
  app:
    image: golang:latest
    ports:
      - "4100:2000"
    environment:
      - AMQP_URL=rabbitmq
    env_file:
      - .env
    volumes:
      - /home/fikri/programming/work/applimetis/medqlabv2/brdiging-hl7:/app
      - /home/fikri/Documents/hl7/orders:/app/hl7/orders
    depends_on:
      - rabbitmq
