version: '3'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    # ports: 
    #   - "0.0.0.0:5100:2000"
    command: ./main
    env_file: 
    - .env
    volumes:
    - ./:/app
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./bot
    depends_on: 
    - main
    env_file: 
    - .env
    volumes:
    - ./:/app
  watcher:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./watcher
    depends_on: 
    - main
    env_file: 
    - .env
    volumes:
    - ./file:/app