version: "3"
services:
  hl7:
    depends_on:
      rabbitmq:
        condition: service_healthy
    container_name: hl7
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4100:2000"
    environment:
      #   - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5673/
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
    env_file:
      - .env
    volumes:
      - /home/fikri/Documents/hl7/result-staging/:/app/results/
      - /home/fikri/Documents/hl7/orders/:/app/orders/
    restart: always
  rabbitmq:
    hostname: rabbitmq
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 3
    restart: always
